/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication31;

import javax.swing.JOptionPane;

/**
 *
 * @author gg
 */
public class combobox extends javax.swing.JFrame {

    /**
     * Creates new form combobox
     */
    public combobox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregar = new javax.swing.JButton();
        campo = new javax.swing.JTextField();
        instruccion = new javax.swing.JLabel();
        materias = new javax.swing.JComboBox<>();
        agregar_todos = new javax.swing.JButton();
        borrar_todos = new javax.swing.JButton();
        seleccion_materia = new javax.swing.JComboBox<>();
        basurero = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        agregar.setText("agregar ");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        instruccion.setText("agregar el nombre de los modulos de los que estas matriculado : ");

        agregar_todos.setText("agregar todos");
        agregar_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_todosActionPerformed(evt);
            }
        });

        borrar_todos.setText("borrar todos");
        borrar_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar_todosActionPerformed(evt);
            }
        });

        seleccion_materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero", "Segundo", "" }));

        basurero.setIcon(new javax.swing.ImageIcon("C:\\Users\\gg\\OneDrive\\Documentos\\GitHub\\pr-ctica-2-3-elementos-combobox-lordyhg12\\media\\trash.png")); // NOI18N
        basurero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basureroActionPerformed(evt);
            }
        });

        titulo.setText("materias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(borrar_todos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregar)
                        .addGap(254, 254, 254)
                        .addComponent(agregar_todos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(instruccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seleccion_materia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(materias, 0, 130, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(basurero))
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccion_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titulo)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basurero))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(agregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(agregar_todos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(borrar_todos)
                .addGap(54, 54, 54))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed

        boolean repetido = false;
        if (!(campo.getText().isEmpty())){
        for (int i = 0; i < materias.getItemCount(); i++) {
            repetido = false;
            if (materias.getItemAt(i).equalsIgnoreCase(campo.getText())) {
                repetido = true;
                break;
            }
        }
        if (repetido == false ) {
            materias.addItem(campo.getText());
        } else {
            JOptionPane.showMessageDialog(null, "materia repetida");
        }
        campo.setText("");
        }else{
           JOptionPane.showMessageDialog(null, "el campo no puede estar vacio ");
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void agregar_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_todosActionPerformed

        String primero[] = {"sistemas", "programacion", "lenguaje de marcas", "fol", "entornos de desarrollo", "base de datos"};
        String segundo[] = {"ingles", "acceso a datos", "empresa", "desarrollo de interfacez", "dispositivos moviles", "procesos y servicios"};

        String valor = (String) seleccion_materia.getSelectedItem();

        if (valor.equalsIgnoreCase("Primero")) {
            if (materias.getItemCount() < 6) {
                for (int i = 0; i < primero.length; i++) {

                    materias.addItem(primero[i]);
                }
            } else {
                
                    JOptionPane.showMessageDialog(null, "ya te inscribiste en un curso  ");
               
            }
        }

        if (valor.equalsIgnoreCase("Segundo")) {
            if (materias.getItemCount() < 6) {
                for (int i = 0; i < segundo.length; i++) {

                    materias.addItem(segundo[i]);
                }
            } else {
               
                    JOptionPane.showMessageDialog(null, "ya te inscribiste en un curso  ");
              
            }
        }
    }//GEN-LAST:event_agregar_todosActionPerformed

    private void borrar_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar_todosActionPerformed

        materias.removeAllItems();
    }//GEN-LAST:event_borrar_todosActionPerformed

    private void basureroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basureroActionPerformed
       
        
        for (int i = 0; i <materias.getItemCount(); i++) {
            if(i==materias.getSelectedIndex()){
                materias.removeItemAt(i);
            }
            
        }
         
        
        
        
    }//GEN-LAST:event_basureroActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new combobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton agregar_todos;
    private javax.swing.JButton basurero;
    private javax.swing.JButton borrar_todos;
    private javax.swing.JTextField campo;
    private javax.swing.JLabel instruccion;
    private javax.swing.JComboBox<String> materias;
    private javax.swing.JComboBox<String> seleccion_materia;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
